// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230926040426_RiderEntityUpdatedV2")]
    partial class RiderEntityUpdatedV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.22");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BikeChasis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MulkiyaNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("API.Entities.Rider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmExpiredate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmIssuedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmirateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabourCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LbExpiredate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LbIssuedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RriderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisaCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisaSponsor")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Riders");
                });

            modelBuilder.Entity("API.Entities.RiderBikeAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BikeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BikeId")
                        .IsUnique();

                    b.HasIndex("RiderId")
                        .IsUnique();

                    b.ToTable("RiderBikeAssociations");
                });

            modelBuilder.Entity("API.Entities.RiderBikeAssociation", b =>
                {
                    b.HasOne("API.Entities.Bike", "Bike")
                        .WithOne("RiderBikeAssociation")
                        .HasForeignKey("API.Entities.RiderBikeAssociation", "BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Rider", "Rider")
                        .WithOne("RiderBikeAssociation")
                        .HasForeignKey("API.Entities.RiderBikeAssociation", "RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("API.Entities.Bike", b =>
                {
                    b.Navigation("RiderBikeAssociation");
                });

            modelBuilder.Entity("API.Entities.Rider", b =>
                {
                    b.Navigation("RiderBikeAssociation");
                });
#pragma warning restore 612, 618
        }
    }
}
